// GENERATED by scripts/allergen-words/gen.ts from src/lib/allergens.ts: do not hand-edit (api/__tests__/allergenWords.test.js
// checks the two agree). Which foods hold a label allergen, by the words in a dish's name and description.

/** label allergen id → words in a food's name that mean it is in there */
export const FOUND_IN = {
  milk: ["milk","milks","dairy","cheese","cheeses","paneer","curd","curds","dahi","yogurt","yogurts","yoghurt","yoghurts","ghee","butter","buttermilk","cream","creamy","lassi","raita","kheer","khoa","khoya","malai","whey","casein","chaas","latte","cappuccino","custard","kulfi","rasmalai","milkshake","mozzarella","cheddar","parmesan","feta","ricotta","labneh","tzatziki","halloumi","kefir","shrikhand","basundi","rabri","mawa"],
  eggs: ["egg","eggs","omelette","omelettes","omelet","frittata","mayo","mayonnaise","meringue","quiche","anda","custard"],
  fish: ["fish","fishes","salmon","tuna","cod","haddock","mackerel","sardine","sardines","anchovy","anchovies","trout","tilapia","basa","pomfret","rohu","hilsa","surmai","bangda","kipper","kippers","pollock","hake","seabass","halibut","snapper","catla","katla","swordfish","fishcake","fishcakes","hammour","grouper","bass","seabass","barramundi","kingfish","worcestershire"],
  crustaceans: ["prawn","prawns","shrimp","shrimps","crab","crabs","lobster","lobsters","crayfish","langoustine","langoustines","scampi","krill","shellfish","seafood"],
  molluscs: ["mussel","mussels","oyster","oysters","clam","clams","squid","calamari","octopus","scallop","scallops","snail","snails","escargot","cuttlefish","whelk","whelks","cockle","cockles","abalone","shellfish","seafood"],
  nuts: ["nut","nuts","almond","almonds","badam","cashew","cashews","kaju","walnut","walnuts","akhrot","pistachio","pistachios","pista","hazelnut","hazelnuts","pecan","pecans","macadamia","macadamias","praline","marzipan","nutella"],
  peanuts: ["peanut","peanuts","groundnut","groundnuts","moongphali","mungfali","satay","chikki"],
  soya: ["soy","soya","soybean","soybeans","soyabean","soyabeans","tofu","edamame","tempeh","miso","natto"],
  wheat: ["wheat","gluten","bread","breads","toast","roti","rotis","chapati","chapatis","chapatti","phulka","naan","paratha","parathas","puri","puris","poori","bhatura","bhature","kulcha","pasta","spaghetti","macaroni","noodle","noodles","couscous","semolina","sooji","suji","rava","upma","maida","atta","bulgur","dalia","daliya","seitan","barley","rye","spelt","cracker","crackers","biscuit","biscuits","cookie","cookies","cake","cakes","croissant","croissants","bagel","bagels","pizza","pita","pitta","sandwich","sandwiches","samosa","samosas","thepla","wrap","wraps"],
  celery: ["celery","celeriac"],
  mustard: ["mustard","sarson"],
  sesame: ["sesame","tahini","tahina","hummus","houmous","hommus","gingelly","halva","ganoush","ghanoush","zaatar","atar","dukkah","gomasio","gomashio","falafel"],
  "sulphur dioxide": ["sulphite","sulphites","sulfite","sulfites","wine"],
  lupin: ["lupin","lupine"],
};
/** "coconut milk", "peanut butter": the word before says it isn't dairy */
export const NOT_DAIRY_BEFORE = ["coconut","almond","soy","soya","oat","rice","cashew","peanut","cocoa","apple","nut","shea","plant","vegan"];

const FREE_OF = /\b(\w+)[- ]free\b|\bno (\w+)\b|\bwithout (\w+)\b/g;
const wordsOf = (text) => String(text).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').match(/[a-z]+/g) ?? [];

function hasLabelAllergen(id, words, freeOf) {
  if (freeOf.has(id) || (id === 'wheat' && freeOf.has('gluten')) || (id === 'milk' && (freeOf.has('dairy') || freeOf.has('lactose')))) return false;
  const list = FOUND_IN[id] ?? [id];
  return words.some((w, i) => {
    if (!list.includes(w)) return false;
    if (id === 'milk' && ['milk', 'milks', 'butter', 'cream'].includes(w) && NOT_DAIRY_BEFORE.includes(words[i - 1])) return false;
    if (id === 'nuts' && ['nut', 'nuts'].includes(w) && ['pea', 'ground', 'coco', 'dough', 'butter', 'pine'].includes(words[i - 1])) return false;
    return true;
  });
}

/** Which of these label allergen ids (lower case) the dish's text shows: "hummus" is sesame, "yoghurt" is milk. */
export function labelAllergensIn(text, allergyIds) {
  const contents = String(text).split(/may contain|traces of|made in a|produced in a|manufactured in|packed in a|made on a/i)[0];
  const words = wordsOf(contents);
  const freeOf = new Set();
  for (const m of contents.toLowerCase().matchAll(FREE_OF)) freeOf.add(m[1] ?? m[2] ?? m[3]);
  if (freeOf.has('egg')) freeOf.add('eggs');
  if (freeOf.has('nut')) freeOf.add('nuts');
  return allergyIds.filter(a => Object.hasOwn(FOUND_IN, a) && hasLabelAllergen(a, words, freeOf));
}
