// The server's copy of the app's label-allergen word lists (api/_lib/allergenWords.js, generated by scripts/allergen-words/gen.ts)
// must give the same answers as the app (src/lib/allergens.ts). If one of these fails, run: npx vite-node scripts/allergen-words/gen.ts
import { describe, expect, it } from 'vitest';
import { FOUND_IN as appFoundIn, NOT_DAIRY_BEFORE as appNotDairy, LABEL_ALLERGENS, allergiesIn } from '../../src/lib/allergens';
import { FOUND_IN, NOT_DAIRY_BEFORE, labelAllergensIn } from '../_lib/allergenWords.js';
import { LABEL_ALLERGENS as SERVER_LABELS } from '../_lib/ideaFilter.js';

const TEXTS = [
  'hummus with pitta', 'Tahini dressing', 'Greek yoghurt with berries', 'coconut milk curry', 'oat milk latte', 'peanut butter toast', 'Peanut butter and jam',
  'butter chicken', 'Gluten-free bread', 'dairy free cheese', 'no nuts granola', 'without egg mayo', 'prawn cocktail', 'tofu stir fry', 'Salad with za’atar',
  'falafel wrap', 'celery soup', 'mustard greens', 'wine gravy', 'lupin flour pasta', 'Chocolate (may contain nuts)', 'tomato soup', 'Mixed nuts and raisins',
  'ground nut oil', 'Cafe latte', 'Rotí con crème', 'Baba ganoush', 'Almond milk shake', 'Paneer tikka', 'Rice and dal',
];

describe('the server’s allergen words match the app’s', () => {
  it('has the same lists', () => {
    expect(FOUND_IN).toEqual(appFoundIn);
    expect(NOT_DAIRY_BEFORE).toEqual(appNotDairy);
  });

  it('names the same 14 label allergens', () => {
    expect([...SERVER_LABELS].sort()).toEqual([...LABEL_ALLERGENS].sort());
  });

  it('gives the same answer for every sample dish and allergen', () => {
    for (const text of TEXTS) expect(labelAllergensIn(text, LABEL_ALLERGENS), text).toEqual(allergiesIn(text, LABEL_ALLERGENS));
  });
});
