// Writes api/_lib/allergenWords.js from src/lib/allergens.ts, so the server (api/suggest-meals.js) knows which foods hold a label
// allergen exactly as the app does. Run it after editing FOUND_IN / NOT_DAIRY_BEFORE:
//   npx vite-node scripts/allergen-words/gen.ts
// (api/__tests__/allergenWords.test.js fails when the two differ.)
import { writeFileSync } from 'node:fs';
import { FOUND_IN, NOT_DAIRY_BEFORE } from '../../src/lib/allergens';

const lines = Object.entries(FOUND_IN).map(([id, words]) => `  ${/^[a-z]+$/.test(id) ? id : JSON.stringify(id)}: ${JSON.stringify(words)},`);
const out = `// GENERATED by scripts/allergen-words/gen.ts from src/lib/allergens.ts: do not hand-edit (api/__tests__/allergenWords.test.js
// checks the two agree). Which foods hold a label allergen, by the words in a dish's name and description.

/** label allergen id → words in a food's name that mean it is in there */
export const FOUND_IN = {
${lines.join('\n')}
};
/** "coconut milk", "peanut butter": the word before says it isn't dairy */
export const NOT_DAIRY_BEFORE = ${JSON.stringify(NOT_DAIRY_BEFORE)};

const FREE_OF = /\\b(\\w+)[- ]free\\b|\\bno (\\w+)\\b|\\bwithout (\\w+)\\b/g;
const wordsOf = (text) => String(text).toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g, '').match(/[a-z]+/g) ?? [];

function hasLabelAllergen(id, words, freeOf) {
  if (freeOf.has(id) || (id === 'wheat' && freeOf.has('gluten')) || (id === 'milk' && (freeOf.has('dairy') || freeOf.has('lactose')))) return false;
  const list = FOUND_IN[id] ?? [id];
  return words.some((w, i) => {
    if (!list.includes(w)) return false;
    if (id === 'milk' && ['milk', 'milks', 'butter', 'cream'].includes(w) && NOT_DAIRY_BEFORE.includes(words[i - 1])) return false;
    if (id === 'nuts' && ['nut', 'nuts'].includes(w) && ['pea', 'ground', 'coco', 'dough', 'butter', 'pine'].includes(words[i - 1])) return false;
    return true;
  });
}

/** Which of these label allergen ids (lower case) the dish's text shows: "hummus" is sesame, "yoghurt" is milk. */
export function labelAllergensIn(text, allergyIds) {
  const contents = String(text).split(/may contain|traces of|made in a|produced in a|manufactured in|packed in a|made on a/i)[0];
  const words = wordsOf(contents);
  const freeOf = new Set();
  for (const m of contents.toLowerCase().matchAll(FREE_OF)) freeOf.add(m[1] ?? m[2] ?? m[3]);
  if (freeOf.has('egg')) freeOf.add('eggs');
  if (freeOf.has('nut')) freeOf.add('nuts');
  return allergyIds.filter(a => Object.hasOwn(FOUND_IN, a) && hasLabelAllergen(a, words, freeOf));
}
`;
writeFileSync(new URL('../../api/_lib/allergenWords.js', import.meta.url), out);
console.log('wrote api/_lib/allergenWords.js:', Object.keys(FOUND_IN).length, 'allergens');
